[versions]
gradle-android-plugin = "7.2.2"

kotlin = "1.8.0"

coroutine = "1.6.4"

android-minSdk = "24"
android-compileSdk = "33"
android-targetSdk = "33"

androidx = "1.10.1"
androidx-appcompat = "1.6.1"
androidx-activity-ktx = "1.7.2"
androidx-fragment-ktx = "1.5.7"
androidx-annotation = "1.5.0"
androidx-recyclerview = "1.2.1"
androidx-constraintlayout = "2.1.0"
andoridx-test-ext-junit = "1.1.5"
andoridx-test-espresso = "3.4.0"

lifecycle = "2.4.1"

compose-compiler = "1.4.0"
compose-activity = "1.4.0"
compose-bom = "2023.01.00"
compose-constraint-layout = "1.0.1"
navigation-compose = "2.4.2"

test-junit = "4.13.2"
retrofit = "2.9.0"
okhttp = "4.9.3"
gson = "2.9.0"
room = "2.4.3"
hilt = "2.46.1"


[plugins]

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "gradle-android-plugin" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }

androidx-core = { module = "androidx.core:core", version.ref = "androidx" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity-ktx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment-ktx" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }

kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

lifecycle-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-testing = { module = "androidx.lifecycle:lifecycle-runtime-testing", version.ref = "lifecycle" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
coroutine-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }
coroutine-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutine" }

compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "compose-constraint-layout" }

test-junit = { module = "junit:junit", version.ref = "test-junit" }
test-compose-ui-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
test-androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "andoridx-test-espresso" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

room = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }


[bundles]
compose = ["compose-activity", "compose-animation", "compose-ui", "compose-material3", "compose-constraintlayout", "compose-ui-tooling", "compose-ui-tooling", "compose-ui-preview", "compose-foundation"]
